name: First Interaction

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "¡Gracias por abrir tu primer issue! Nuestro equipo lo revisará pronto."
        pr-message: "¡Felicidades por tu primer pull request! Apreciamos tu contribución."
